### ISSUE TITLE
Notifications on Main thread or no?

### ISSUE THREAD

**Issue by ynnadrules** [ashleymills/Reachability.swift#70] opened 2015-12-20 22:54 UTC
In the README, you state that the notifications are delivered on the main thread, but `startNotifier` posts the notification on a different thread at least once: 

```Swift
public func startNotifier() throws {

  // ...

  // Perform an intial check
  dispatch_async(reachabilitySerialQueue) { () -> Void in
      let flags = self.reachabilityFlags
      self.reachabilityChanged(flags)
  }
  
  // ...
}
```

I noticed that the callback passed to `SCNetworkReachabilitySetCallback` does call `reachabilityChanged` on the main thread. 

Is the README wrong? Am I meant to be dispatching async to the main queue in my notification handler? 

Thanks!

**Comment by puttin** [comment] 2015-12-25 06:18
I dispatch_async to make sure it's not on mainQueue by myself about this problem

**Comment by ynnadrules** [comment] 2015-12-28 14:10
Yeah that's what I had to do. So I'm going to guess the README is wrong.

**Comment by ryanhurley** [comment] 2016-01-21 17:48
I'm also getting errors in my console due to the self.reachabilityChanged(flags) call. For those who need a workaround, just add dispatch_async(dispatch_get_main_queue())  around any code in your reachabilityChanged method that needs the main thread (UI changes mostly)

For example: 
 dispatch_async(dispatch_get_main_queue()) {
    // Show alert view, reload data data, etc
}

**Comment by Slruh** [comment] 2016-01-21 17:54
Also getting the same error after following the readme. For those who need a work around, simply add dispatch_async(dispatch_get_main_queue()) around code that needs to run on the main thread (this is usually code that changes the UI).

For example: 
``` swift
    func reachabilityChanged(note: NSNotification) {
        let reachability = note.object as! Reachability
        
        dispatch_async(dispatch_get_main_queue()) {
            if reachability.isReachable() {
                // Update UI, reload table data, etc
            } else {
                // Show UIAlert or other error message
            }
        }
    }
```

**Comment by DagAgren** [comment] 2016-03-04 08:08
This doesn't seem like a documentation problem. The documentation documents the reasonable behaviour, and the code should be fixed to match the documentation.

The problem is that startNotifier() calls reachabilityChanged on a background thread here:

https://github.com/ashleymills/Reachability.swift/blob/master/Reachability/Reachability.swift#L160

I'm not sure about the exact subtle details about the threading here, but it seems the reachabilityChanged() call should be wrapped in another dispatch call back to the main thread, similar to the other call site:

https://github.com/ashleymills/Reachability.swift/blob/master/Reachability/Reachability.swift#L45

**Closed** 2016-09-30 16:03 UTC
Labels: Documentation
